### ISSUE TITLE
Pretrained model and workflow

### ISSUE THREAD

**Issue by spacewalkingninja** [ZhangXu0963/2023ICME-VSL#1]
Where do I download your model? How can I turn it on. I need img 2 txt thing runniong on my pc.

**Comment by ZhangXu0963** [comment]
> Where do I download your model? How can I turn it on. I need img 2 txt thing runniong on my pc.

I am preparing the complete model, code and readme, and will publish as soon as possible

**Comment by ZhangXu0963** [comment]
> Where do I download your model? How can I turn it on. I need img 2 txt thing runniong on my pc.

I updated the code.

**Comment by xyi007** [comment]
> Where do I download your model? How can I turn it on. I need img 2 txt thing runniong on my pc.

Can you run it on the f30k dataset?
